services:
    sonata.admin.employee:
        class: AppBundle\Admin\EmployeeAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Employees" }
        arguments:
           - ~
           - AppBundle\Entity\Employee
           - ~
        calls:
           - [ setTranslationDomain, [messages]]

    sonata.admin.role:
        class: AppBundle\Admin\RoleAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "Hidden", label: "Roles" }
        arguments:
           - ~
           - AppBundle\Entity\Role
           - ~
        calls:
           - [ setTranslationDomain, [messages]]

    sonata.admin.performance:
        class: AppBundle\Admin\PerformanceAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Performances" }
        arguments:
           - ~
           - AppBundle\Entity\Performance
           - ~
        calls:
           - [ setTranslationDomain, [messages]]

    sonata.admin.performanceEvent:
        class: AppBundle\Admin\PerformanceEventAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "PerformanceEvents" }
        arguments:
           - ~
           - AppBundle\Entity\PerformanceEvent
           - ~
        calls:
           - [ setTranslationDomain, [messages]]
           - [ setTemplate, [edit, AppBundle:PostAdmin:edit.html.twig]]

    sonata.admin.post:
        class: AppBundle\Admin\PostAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Posts" }
        arguments:
           - ~
           - AppBundle\Entity\Post
           - ~
        calls:
        - [ setTranslationDomain, [messages]]
        - [ setParameters, ['%sonata_translation.default_locale%', '%sonata_translation.locales%']]

    sonata.admin.tag:
        class: AppBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Tags" }
        arguments:
            - ~
            - AppBundle\Entity\Tag
            - ~
        calls:
        - [ setTranslationDomain, [messages]]

    sonata.admin.history:
        class: AppBundle\Admin\HistoryAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "History" }
        arguments:
           - ~
           - AppBundle\Entity\History
           - ~
        calls:
        - [ setTranslationDomain, [messages]]

    sonata.admin.venue:
        class: AppBundle\Admin\VenueAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Venue" }
        arguments:
           - ~
           - AppBundle\Entity\Venue
           - ~
        calls:
        - [ setTranslationDomain, [messages]]
