services:
   sonata.admin.employee:
       class: AppBundle\Admin\EmployeeAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Employees" }
       arguments:
           - ~
           - AppBundle\Entity\Employee
           - ~
       calls:
           - [ setTranslationDomain, [AppBundle]]

   sonata.admin.role:
       class: AppBundle\Admin\RoleAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: "Hidden", label: "Roles" }
       arguments:
           - ~
           - AppBundle\Entity\Role
           - ~
       calls:
           - [ setTranslationDomain, [AppBundle]]

   sonata.admin.performance:
       class: AppBundle\Admin\PerformanceAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Performances" }
       arguments:
           - ~
           - AppBundle\Entity\Performance
           - ~
       calls:
           - [ setTranslationDomain, [AppBundle]]

   sonata.admin.performanceEvent:
       class: AppBundle\Admin\PerformanceEventAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "PerformanceEvents" }
       arguments:
           - ~
           - AppBundle\Entity\PerformanceEvent
           - ~
       calls:
           - [ setTranslationDomain, [AppBundle]]

   sonata.admin.post:
       class: AppBundle\Admin\PostAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Posts" }
       arguments:
           - ~
           - AppBundle\Entity\Post
           - ~
       calls:
       - [ setTranslationDomain, [AppBundle]]

   sonata.admin.tag:
       class: AppBundle\Admin\TagAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: "Hidden", label: "Tags" }
       arguments:
           - ~
           - AppBundle\Entity\Tag
           - ~
       calls:
       - [ setTranslationDomain, [AppBundle]]
