services:
    sonata.admin.employee:
        class: AppBundle\Admin\EmployeeAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Employees" }
        arguments:
           - ~
           - AppBundle\Entity\Employee
           - ~
        calls:
           - [ setTranslationDomain, [messages]]

    sonata.admin.role:
        class: AppBundle\Admin\RoleAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "Hidden", label: "Roles" }
        arguments:
           - ~
           - AppBundle\Entity\Role
           - ~
        calls:
           - [ setTranslationDomain, [messages]]

    sonata.admin.performance:
        class: AppBundle\Admin\PerformanceAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Performances" }
        arguments:
           - ~
           - AppBundle\Entity\Performance
           - ~
        calls:
           - [ setTranslationDomain, [messages]]

    sonata.admin.performanceEvent:
        class: AppBundle\Admin\PerformanceEventAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "PerformanceEvents" }
        arguments:
           - ~
           - AppBundle\Entity\PerformanceEvent
           - ~
        calls:
           - [ setTranslationDomain, [messages]]

    sonata.admin.post:
        class: AppBundle\Admin\PostAdmin
        tags:
           - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Posts" }
        arguments:
           - ~
           - AppBundle\Entity\Post
           - ~
        calls:
        - [ setTranslationDomain, [messages]]
        - [ setContainer, [@service_container]]

    sonata.admin.tag:
        class: AppBundle\Admin\TagAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "CheTheatre", label: "Tags" }
        arguments:
            - ~
            - AppBundle\Entity\Tag
            - ~
        calls:
        - [ setTranslationDomain, [messages]]
