security:
    providers:
        in_memory:
            memory:
              users:
                admin: { password: %admin_password%, roles: 'ROLE_SUPER_ADMIN'}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        secured_area:
            pattern:  ^%admin_dashboard_base_url%/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  %admin_dashboard_base_url%/login_check
                default_target_path: sonata_admin_dashboard
            logout:
                path:   %admin_dashboard_base_url%/logout
                target: /login

    role_hierarchy:
            ROLE_SONATA_FOO_ADMIN:
                - ROLE_SONATA_ADMIN_DEMO_FOO_DELETE
                - ROLE_SONATA_ADMIN_DEMO_FOO_EXPORT
                - ROLE_SONATA_ADMIN_DEMO_FOO_CREATE
                - ROLE_SONATA_ADMIN_DEMO_FOO_EDIT
                - ROLE_SONATA_ADMIN_DEMO_FOO_LIST
                - ROLE_SONATA_ADMIN_DEMO_FOO_VIEW
                - ROLE_ADMIN
                - ROLE_USER
                - ROLE_SONATA_ADMIN
            ROLE_SUPER_ADMIN: [ROLE_SONATA_FOO_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    access_control:
            - { path: ^%admin_dashboard_base_url%/, roles: ROLE_SUPER_ADMIN }

    encoders:
          Symfony\Component\Security\Core\User\User: plaintext
