sonata_admin:
    title:      %sonata_admin.title%
    title_logo: %sonata_admin.logo_title%

    templates:
        edit: ::SonataAdmin/CRUD/edit.html.twig
    dashboard:
        groups:
            CheTheatre:
                label: Main.Panel
                label_catalogue: AppBundle
            sonata_media:
                label: Media.Library
                label_catalogue: AppBundle
#            Hidden:

        blocks:
            -
                position: left
                type: sonata.admin.block.admin_list
                settings:
                    groups: [CheTheatre]
            -
                position: right
                type: sonata.admin.block.admin_list
                settings:
                    groups: [sonata_media, Hidden]

sonata_doctrine_orm_admin:
    templates:
        form: [:SonataAdmin:form_admin_fields.html.twig]
