sonata_admin:
    title:      %sonata_admin.title%
    title_logo: %sonata_admin.logo_title%

    security:
       handler: sonata.admin.security.handler.role

    templates:
        layout: ::SonataAdmin/standard_layout.html.twig
        edit: ::SonataAdmin/CRUD/edit.html.twig

    dashboard:
        groups:
            CheTheatre:
                label: Dashboard
                label_catalogue: SonataAdminBundle
#            sonata_media:
#                label: Медіа (сховати в майбутньому)
#                label_catalogue: AppBundle

        blocks:
            -
                position: left
                class: col-md-10
                type: sonata.admin.block.admin_list
                settings:
                    groups: [CheTheatre]
            -
                position: right
                class: col-md-6
                type: sonata.block.service.text
                settings:
                    content: >
                        <h3 style="text-align: center"><code>Вітаємо Вас в Адміністративній Панелі</code></h3>
                        <h4 style="text-align: center">Черкаського академічного обласного українського</h4>
                        <h4 style="text-align: center">музично-драматичного театру ім. Т.Г.Шевченка</h4>
                        <p style="text-align: center"><code>Контакти розробників:</code></p>
                        <p style="text-align: center">Сергій <code>spolischook@gmail.com</code></p>
                        <p style="text-align: center"> Світлана <code>+38(093)-702-06-44</code></p>
#            -
#                position: right
#                type: sonata.admin.block.admin_list
#                settings:
#                    groups: [sonata_media, Hidden]

    assets:
        javascripts: # changed order of js assets loading
            - js/jquery-2.1.0.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonataadmin/vendor/select2/select2.min.js
            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js

sonata_doctrine_orm_admin:
    templates:
        form: [:SonataAdmin:form_admin_fields.html.twig]
